name: bluDemocracy
favicon: null
layout_spectrum: 0.25352
typography_spectrum: 0.4944404289126396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080607'
    - '#8fc1fe'
    - '#5e382b'
    - '#d09c77'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
